Added header
emerell/device pull request #2
Opened 2018-12-07 00:15 UTC by emerell

2018-12-10 11:23 UTC, kryvonos-v commented on index.html
> +            <div class="header__feature">
Тег `<div>` не може бути диною тега `<ul>`

2018-12-10 11:24 UTC, kryvonos-v requested changes
Провалідуй свій html документ https://validator.w3.org/nu/#textarea

2018-12-10 11:43 UTC, kryvonos-v reviewed
![device header when search input focused](https://user-images.githubusercontent.com/29276196/49730509-3bdb2b00-fc81-11e8-9d32-b1e038848cda.png)
![device header](https://user-images.githubusercontent.com/29276196/49730510-3c73c180-fc81-11e8-8be6-f31a5aef8cca.png)

1) Коли поле для пошуку стає у фокусі, то з'являється кнопка "Найти" яка збільшує висоту батька. За рахунок сайт наче дьоргається. Ти можеш побачити цей ефект якщо кожну з фотокою відкриєш у окремій вкладці
2) Логотип спозиціонований не так як на макеті
3) Зроби більші відступи між пунктами меню "доставка", "гарантия" і тд, щоб було можна легше тапнути по них на мобільних пристроях
4) Заданий більший відступ зверху для пункта меню "Виртуальная реальность" і такий же відступ знизу для пункта "Квадрокоптеры"
5) Молодець, що оживила меню через JS :)
6) Зроби ще так щоб ікона пошуку і ікона пункта меню "войти" вирівнювался по одній вертикальній лінії

![screen shot 2018-12-10 at 2 25 50 pm](https://user-images.githubusercontent.com/29276196/49732486-8a8bc380-fc87-11e8-850e-3aeceb94451b.png)
- Зроби щоб ця кнопка при :hover i :focus мала однакові стилі. Тоді для неї буде можна поставити `outline: none;`

2018-12-10 12:03 UTC, kryvonos-v commented on styles/components/search/output.scss
> +  background-color: $color-text;
Для пошуку можна задати прозорий фон: `background-color: transparent;`. Таким чином фоновий колір елемента буде такий самий як і у батька.

2018-12-10 12:06 UTC, kryvonos-v commented on styles/components/search/output.scss
> +  border: 2px solid $color-text;
![screen shot 2018-12-10 at 2 03 51 pm](https://user-images.githubusercontent.com/29276196/49731563-71354800-fc84-11e8-8bf1-4909c1aaaf05.png)

Рамка потрібна лише знизу, тому краще написати:
```css
.search__input {
  boder: none;
  border-bottom: 2px solid transparent;
}
```
Оскільки рамка знизу повинна бути видима лише при фокусі, то ми початково робимо її прозорою

2018-12-10 12:07 UTC, kryvonos-v commented on styles/components/search/output.scss
> +  border-bottom: 2px solid $color-primary-text;
Ти для класу `.search__input` вже визначила товщину і тип рамки, тому єдине, що тобі потрібно тут зробити це перевизначити колір рамки знизу: `border-bottom-color: $color-primary-text;`

2018-12-10 12:08 UTC, kryvonos-v reviewed
![screen shot 2018-12-10 at 2 07 38 pm](https://user-images.githubusercontent.com/29276196/49731728-fc164280-fc84-11e8-8524-5f0dd8ae923f.png)

При кліку на іконку лупи пошук повинен стати у фокусі. А зараз нічого не відбувається

2018-12-10 12:11 UTC, kryvonos-v commented on styles/components/catalog/output.scss
> +.catalog-item {
Це вже новий БЕМ блок, тому його потрібно винести в окремий файл

2018-12-10 12:12 UTC, kryvonos-v commented on styles/elements/feature-button/output.scss
> +.popular-item__navigation {
Що цей БЕМ елемент забувся у файлі `feature-button`?)

2018-12-10 12:13 UTC, kryvonos-v commented on styles/elements/feature-button/output.scss
> +.popular-item__button-wrapper {
Те саме стосується і цього елемента)

2018-12-10 12:16 UTC, kryvonos-v commented on styles/components/header/output.scss
> +  .section {
Ми домовлялися, що не будемо писати такі вкладені селектори. Тому якщо хочеш задати ці стилі, то створи елемент `.header__section` або `.header__inner` і вже туди додавай їх.

2018-12-10 12:17 UTC, kryvonos-v commented on styles/components/header/output.scss
> +    &--large {
З цим вкладеним селектором теж потрібно щось зробити

2018-12-10 12:20 UTC, kryvonos-v commented on styles/components/header/output.scss
> +  margin-top: 1rem;
Краще додай цей margin до елемента `.header__feature-box`. Таким чином ти будеш мати трохи стійкіші стилі до змін. Тобто якщо ти видалиш свій елемент з пошуком, то логотипом і елементами меню всерівно буде гарний відступ

2018-12-10 12:21 UTC, kryvonos-v commented on styles/components/header/output.scss
> +  margin-top: 1rem;
Це насправді дуже маленька деталь

2018-12-10 12:22 UTC, kryvonos-v commented on styles/components/header/output.scss
> +  margin-top: 1rem;
Ось приклад того як воно буде працювати коли видалити пошук і задатий такий margin як я казав

![screen shot 2018-12-10 at 2 20 31 pm](https://user-images.githubusercontent.com/29276196/49732327-e99d0880-fc86-11e8-9e33-4897283ccf43.png) ![screen shot 2018-12-10 at 2 20 43 pm](https://user-images.githubusercontent.com/29276196/49732335-f02b8000-fc86-11e8-9104-32a1462299d5.png)

Ось як зараз виглядає

![screen shot 2018-12-10 at 2 22 06 pm](https://user-images.githubusercontent.com/29276196/49732355-046f7d00-fc87-11e8-806b-54df6008ad9c.png)

Ще раз повторюся, що це дрібниця і те як ти зробила - це теж правильно!

2018-12-10 14:53 UTC, kryvonos-v commented on styles/components/category/output.scss
> +  @include tablet {
У тебе вже є зверху media queries для планшета, тому ці стиі теже перенеси туди

2018-12-10 15:18 UTC, kryvonos-v commented on styles/components/popular-item/output.scss
> +    top: -32px
Накладання цієї секції на шапку сайта краще робити через від'ємний `margin-top`

2018-12-10 15:28 UTC, kryvonos-v reviewed
![screen shot 2018-12-10 at 5 27 44 pm](https://user-images.githubusercontent.com/29276196/49742308-f0387980-fca0-11e8-8e00-b4a735994228.png)
З картинкою дрона біда - не зберігається співвідношення сторін

2018-12-10 15:28 UTC, kryvonos-v commented on index.html
> +              <div class="popular-item-box">
Тут можна обійтися без цієї обгортки

2018-12-10 15:28 UTC, kryvonos-v commented on index.html
> +              <span class="popular-item__number">01</span>
Цифру буде логічніше перенести у середину елемента з класом `.popular-item__info`

2018-12-11 17:25 UTC, taran-d approved these changes

2018-12-11 17:32 UTC, merged